version: '3.4'

services:

  movieticket:
    image: movieticket
    build:
      context : .
      dockerfile : MovieTicket.UI/Dockerfile
    environment:
    - ASPNETCORE_ENVIRONMENT=Development
    ports:
    - 3461:80
